name: hourly-sync
on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Run prisma migrate (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Run sync script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MARKET_API_BASE: ${{ secrets.MARKET_API_BASE }}
          MARKET_API_KEY: ${{ secrets.MARKET_API_KEY }}
        run: node scripts/sync-prices.js
